#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--linux-packages "linux-image-5.19.0-0.deb11.2 linux-headers-5.19.0-0.deb11.2" \
	--source "${_SOURCE}" \
	--backports true \
"${@}"
